### ISSUE TITLE
Uploaded video files do not display thumbnails

### ISSUE THREAD

**Issue by garyvalue** [mindhuntr/dark-send#1]
may need to customize the thumbnail during upload

Also, can we improve the upload speed?
Can multiple sessions be started simultaneously to upload different files?

**Comment by mindhuntr** [comment]
Telegram seems to limit the upload speed when we use their API. I have used FastTelethon.py to improve speeds but it doesn't have any significant effect.

**Comment by garyvalue** [comment]
Thank you for your reply.
Can I add custom thumbnail parameters? Because sometimes uploaded video files appear black, like this
![image](https://github.com/mindhuntr/dark-send/assets/38098459/a05f0351-d49d-41cf-abab-4bc3f621c5f9)

**Comment by mindhuntr** [comment]
You cannot add custom thumbnails as of now but I will implement that feature and let you know. It should be relatively simple to do

**Comment by mindhuntr** [comment]
I have implemented custom thumbnails. Try it out!

**Comment by garyvalue** [comment]
I will try immediately. 
I'm not sure if this project will provide any ideas for parallel uploading based on Telethon.
https://docs.nekmo.org/telegram-upload/upload_benchmark.html
[issues140](https://github.com/Nekmo/telegram-upload/issues/140)

**Comment by garyvalue** [comment]
`Exception in thread Thread-1 (bar_func):
Traceback (most recent call last):
  File "/home/customer/dark-send/progress_bar.py", line 84, in bar_func
    upload_task = bar.add_task("[green]Up/Down...",total=100) 
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/rich/progress.py", line 1623, in add_task
    self.refresh()
  File "/usr/local/lib/python3.11/dist-packages/rich/progress.py", line 1533, in refresh
    self.live.refresh()
  File "/usr/local/lib/python3.11/dist-packages/rich/live.py", line 241, in refresh
    with self.console:
  File "/usr/local/lib/python3.11/dist-packages/rich/console.py", line 865, in __exit__
    self._exit_buffer()
  File "/usr/local/lib/python3.11/dist-packages/rich/console.py", line 823, in _exit_buffer
    self._check_buffer()
  File "/usr/local/lib/python3.11/dist-packages/rich/console.py", line 2060, in _check_buffer
    self.file.write(text)
UnicodeEncodeError: 'latin-1' codec can't encode character '\u280b' in position 10: ordinal not in range(256)
*** You may need to add PYTHONIOENCODING=utf-8 to your environment ***

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/customer/dark-send/progress_bar.py", line 83, in bar_func
    with Progress(SpinnerColumn(),*Progress.get_default_columns()) as bar: 
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/rich/progress.py", line 1177, in __exit__
    self.stop()
  File "/usr/local/lib/python3.11/dist-packages/rich/progress.py", line 1163, in stop
    self.live.stop()
  File "/usr/local/lib/python3.11/dist-packages/rich/live.py", line 147, in stop
    with self.console:
  File "/usr/local/lib/python3.11/dist-packages/rich/console.py", line 865, in __exit__
    self._exit_buffer()
  File "/usr/local/lib/python3.11/dist-packages/rich/console.py", line 823, in _exit_buffer
    self._check_buffer()
  File "/usr/local/lib/python3.11/dist-packages/rich/console.py", line 2060, in _check_buffer
    self.file.write(text)
UnicodeEncodeError: 'latin-1' codec can't encode character '\u280b' in position 10: ordinal not in range(256)
*** You may need to add PYTHONIOENCODING=utf-8 to your environment ***
Traceback (most recent call last):
  File "/home/customer/dark-send/dark-send", line 243, in <module>
    client.loop.run_until_complete(main())
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/customer/dark-send/dark-send", line 74, in main
    video_handle = await client.upload_file(video,progress_callback=progress_bar.progress,part_size_kb=512) # Upload video with progress 
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/telethon/client/uploads.py", line 678, in upload_file
    result = await self(request)
             ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/telethon/client/users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/telethon/client/users.py", line 87, in _call
    result = await future
             ^^^^^^^^^^^^
telethon.errors.rpcbaseerrors.FloodError: RPCError 420: FLOOD_PREMIUM_WAIT_15 (caused by SaveBigFilePartRequest)`

How can these errors be resolved?
